version: "3"

services:
  ksever:
    image: com.klaxon/kserver:0.0.1-snapshot
    container_name: kserver
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=192.168.31.200
      - DB_PORT=20000
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_NAME=kserver
      - REDIS_HOST=192.168.31.200
      - REDIS_PORT=20011
      - REDIS_PASSWORD=sOmE_sEcUrE_pAsS
    volumes:
      - /home/klaxon/Downloads:/app/download
    restart: always