server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    session:
      timeout: 24h

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kserver?serverTimezone=UTC
    username: root
    password: kserver
    dbcp2:
      max-idle: 20
      min-idle: 10
      initial-size: 10
      max-wait-millis: 10000
  flyway:
    enabled: true
    clean-disabled: true
    out-of-order: false
    encoding: UTF-8
    locations: classpath:db/migration
    validate-on-migrate: true
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  openapi:
    version: v4.0
    license: Apache 2.0
