server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/kserver?serverTimezone=UTC
    username: root
    password: kserver
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait-millis: 10000
  devtools:
    restart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

