server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    session:
      timeout: 24h

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    dbcp2:
      max-idle: 20
      min-idle: 10
      initial-size: 10
      max-wait-millis: 10000
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  session:
    store-type: redis
  flyway:
    enabled: true
    clean-disabled: true
    out-of-order: false
    encoding: UTF-8
    locations: classpath:db/migration
    validate-on-migrate: true
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/**/*.xml

knife4j:
  enable: true
  openapi:
    version: v4.0
    license: Apache 2.0

tmdb:
  api-key: ${TMDB_API_KEY}