server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    session:
      timeout: 24h

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait-millis: 10000
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  session:
    store-type: redis
  devtools:
    restart:
      enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
    mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ffmpeg:
  path:

yt-dlp:
  destination: /app/download/
  cookies-from-browser:
  cookies-path:

app:
  protocol: http
  host: 127.0.0.1
  port: 9001
