server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    session:
      timeout: 24h

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.153:20002/kserver?serverTimezone=UTC
    username: root
    password: kserver
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait-millis: 10000
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  redis:
    host: 192.168.31.153
    port: 20001
    password: sOmE_sEcUrE_pAsS
  session:
    store-type: redis
  devtools:
    restart:
      enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ffmpeg:
  path: D:\Program\Scoop\apps\ffmpeg\5.1.2\bin\ffmpeg.exe

yt-dlp:
  destination: /Users/kail/Downloads/yt-dlp/
  cookies-from-browser: vivaldi:/Users/kail/Library/Application Support/Vivaldi/Default
  cookies-path: D:\Temp\test\www.bilibili.com_cookies.txt

app:
  protocol: http
  host: 127.0.0.1
  port: 9001
